version: '3.8'

services:
  neo4j:
    image: neo4j:2025.12.1-enterprise
    container_name: neo4j_ent_db
    ports:
      - 7474:7474 # HTTP
      - 7473:7473 # HTTPS
      - 7687:7687 # Bolt
    volumes:
        - ./neo4j_home/data:/data :z
        - ./neo4j_home/import:/import
        - ./neo4j_home/logs:/logs :z
        - ./neo4j_home/conf:/conf :z
        - ./neo4j_home/plugins:/plugins
    environment:
      NEO4J_dbms_security_allow__csv__import__from__file__urls: 'true'
      NEO4J_AUTH: neo4j/pwd12345
      NEO4J_dbms_security_procedures_unrestricted: apoc.*, gds.* # Optional, for APOC library access
      NEO4J_apoc_import_file_enabled: true # Optional, if using APOC import features
      # NEO4J_server_directories_import: import # Explicitly sets the import directory (usually default)
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    restart: unless-stopped
